# Generated by Django 5.2.17 on 2026-08-30 09:26

import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_hash', models.CharField(max_length=64)),
                ('question', models.TextField()),
                ('condensed_question', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('refused', models.BooleanField(default=False)),
                ('refusal_reason', models.CharField(blank=True, max_length=200)),
                ('retrieved_chunk_ids', models.JSONField(default=list)),
                ('used_chunk_ids', models.JSONField(default=list)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.IntegerField()),
                ('model', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ContentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(max_length=200, unique=True)),
                ('record_id', models.CharField(db_index=True, max_length=100)),
                ('kind', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
