import json
from pathlib import Path


class CorpusMissing(Exception):
    pass


def load_corpus(path) -> dict:
    """Reads the artifact generated by `npm run content`. Validation already
    happened in scripts/lib/corpus.mjs -- this only reads."""
    path = Path(path)
    if not path.exists():
        raise CorpusMissing(f"{path} not found. Run `npm run content` from the repo root.")
    return json.loads(path.read_text())
